# Generated by Django 5.1.3 on 2024-12-01 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mfa_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='username',
            new_name='name',
        ),
    ]
