# Generated by Django 5.1.3 on 2024-12-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfa_app', '0002_rename_username_userdetails_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='password',
            field=models.CharField(max_length=10),
        ),
    ]
