# Generated by Django 5.1.3 on 2024-12-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfa_app', '0003_alter_userdetails_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
