# Generated by Django 5.1.3 on 2024-12-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfa_app', '0004_alter_userdetails_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='captured_images/'),
        ),
    ]
