# Generated by Django 5.1.3 on 2024-12-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfa_app', '0005_userdetails_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='token',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
